made the helloworld init.d script more robust, added stop and status.

diff --git a/modules/hello_world/files/etc/init.d/helloworld b/modules/hello_world/files/etc/init.d/helloworld
--- a/modules/hello_world/files/etc/init.d/helloworld
+++ b/modules/hello_world/files/etc/init.d/helloworld
@@ -2,19 +2,118 @@
 #
 # helloworld
 
+process_is_alive() {
+	local pid="$1"
+	ps -p $pid | grep $pid > /dev/null 2>&1
+}
+
+check_running_process_matches_recorded_pid() {
+	local pidfile="$1"
+	local pid
+	
+	pid = `cat "$pidfile" 2>/dev/null`
+	if [ "$pid" = '' ];then
+		# could not read the pid, for whatever reason.
+		return 1
+	fi
+	
+	process_is_alive $pid
+}
+
+kill_process() {
+	local pid="$1"
+	local signal="$2"
+	local second
+	
+	kill -"$signal" "$pid"
+	
+	# ensure that the bugger is gone.
+	for second in 0 1 2 3 4 5 6 7 8 9 10; do
+		process_is_alive "$pid"
+		if [ "$?" -ne 0 ];then
+			return 0
+		fi
+		
+		sleep 1
+	done
+	
+	return 1
+}
+
+kill_process_with_recorded_pid() {
+	local pidfile="$1"
+	local pid
+	
+	pid = `cat "$pidfile" 2>/dev/null`
+	if [ "$pid" = '' ];then
+		# if we can't read the pid file, we assume the process is not running
+		return 0
+	fi
+	
+	# Kill gracefully
+	if kill_process "$pid" 15;then
+		return 0
+	fi
+	
+	# Screw this, kill it properly.
+	if kill_process "$pid" 9;then
+		return 0
+	fi
+	
+	return 1
+}
+
+PID_FILE="/var/run/helloworld/helloworld.pid"
+
+
 case $1 in 
 start)
-	java -jar /opt/helloworld/helloworld-1.0-standalone.jar
-	exit $?
+	check_running_process_matches_recorded_pid $PID_FILE
+	if [ "$?" -eq 0 ];then
+		echo "$0 is already running"
+		exit 0
+	fi
+
+	java -jar /opt/helloworld/helloworld-1.0-standalone.jar > /dev/null 2>&1 &
+	
+	if [ "$?" -ne 0 ];then
+		echo "failed to start $0."
+		exit $?
+	fi
+	
+	rm -rf $PID_FILE
+	echo $! > $PID_FILE
+	echo "started $0."
+	exit 0
 	;;
-restart|reload|force-reload)
+stop)
+	kill_process_with_recorded_pid $PID_FILE
+
+	if [ "$?" -eq 0 ];then
+		rm -rf $PID_FILE > /dev/null 2>&1
+		echo "$0 is stopped."
+		exit 0
+	else
+		echo "failed to stop $0."
+		exit 1
+	fi
+	;;
+status)
+	check_running_process_matches_recorded_pid $PID_FILE
+	if [ "$?" -eq 0 ];then
+		echo "$0 is running."
+		exit 0
+	else
+		echo "$0 is not running."
+		exit 1
+	fi
+	;;
+restart)
 	$0 stop
 	$0 start
 	;;
 *)
-	echo "Usage: $0 (start|restart)"
+	echo "Usage: $0 (start|stop|status|restart)"
 	exit 1
 	;;
 esac
-
-exit 0
